services:
  db:
    image: postgres:16-alpine
    container_name: nest_test
    restart: 'always'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=123456

volumes:
  pgdata: